config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :works
  resources :comments
  resources :projects
  get '/users/sign_out' => 'devise/sessions#destroy'
  root to: "projects#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "75x75>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :picture, styles: { medium: "310x180>", thumb: "62x36>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/work.rb
class Work < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :url, :logo)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # before_action :set_project, only: [:index]
  before_filter :authenticate_user!, except: [:index]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to new_project_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project).permit(:title, :url, :description, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about

  end

  def contacts

  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :new, :create]
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to root_path, notice: 'Work was successfully created.' }
      else
        format.html { redirect_to root_path }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:name, :email, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>
    <div class = 'col-md-12 col-sm-12' style="margin-bottom: 10px">
      <%= f.label 'Текст:' %><br>
      <%= f.text_area :text, class: 'form-control' %>
    </div>

    <div class = 'col-md-12 col-sm-12' style="margin-bottom: 10px">
      <%= f.label 'Ссылка:' %><br>
      <%= f.text_field :url, class: 'form-control' %>
    </div>
    <div class = 'col-md-12 col-sm-12' style="margin-bottom: 10px">
      <%= f.label 'Логотип:' %><br>
      <%= f.file_field :logo,  class: 'form-control' %>
    </div>

    <div class="col-md-12 col-sm-12">
      <%= f.button :submit, value: 'Создать', class: 'btn btn-main btn-mr'  %>
    </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center ffh">Комментарии</h1>

<table class="table">
  <thead>
    <tr>
      <th>Text</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.url %></td>
        <td><%= image_tag comment.logo.url(:medium) %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="col-md-12 col-sm-12">
  <%= link_to 'New Comment', new_comment_path, class: "btn btn-default"%>
</div>

app/views/comments/new.html.erb
<h1 class="text-center ffh">Новый комментарий</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Url:</strong>
  <%= @comment.url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @comment.logo.url(:medium) %>
</p>



<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudnine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Poiret+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
</head>
<body>
<!--admin nav-->
  <% if user_signed_in? %>
    <nav class="wrapper">
      <nav class="navbar navbar-default">
        <ul class="nav navbar-nav" style="float: left">
          <li class="nav-button col-md-1 col-sm-3" ><%= link_to 'Главная', root_path %></li>
          <li class="nav-button col-md-1 col-sm-3" ><%= link_to 'Отзывы', comments_path %></li>
          <li class="nav-button col-md-1 col-sm-3" ><%= link_to 'Заказы', works_path %></li>
          <li class="nav-button col-md-1 col-sm-3" ><%= link_to 'Проекты', new_project_path %></li>
        </ul>
        <ul class="nav navbar-nav out-button" style="padding-top: 5px; margin-right: 20px"><%= link_to 'Выход', destroy_user_session_path, :method => :delete%></ul>
      </nav>
    </nav>
  <% end %>



<%= yield %>


</body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>

    <div class="col-md-6" style="margin-bottom: 10px">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="col-md-6" style="margin-bottom: 10px">
      <%= f.label :url %><br>
      <%= f.text_field :url, class: 'form-control'  %>
    </div>



    <div class="col-md-12 col-sm-12">
      <%= f.button :submit, value: 'Создать', class: 'btn btn-main btn-mr'  %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<!--logo field-->
<div class="top-div col-md-12">
  <div class="circle">
    <%= image_tag('logo.png', width: '200px') %>
  </div>
  <p class="ffh top-text">Хотите заказать классный сайт? <br><b>CloudNine</b> Вам поможет!</p>
</div>

<!--project field-->
<div class="main-content">

  <h1 class="text-center ffh">Проекты</h1>
  <div class="container">
    <div class="row">
      <% @projects.each do |project| %>
          <a class="link col-md-6 col-sm-12" href="<%= project.url%>" >
            <div class="project-box ">
              <div class="project-img" style="background: url(<%= project.picture %>) no-repeat;"> </div>
              <div class="title"><%= project.title %></div>
            </div>
          </a>
      <% end %>
    </div>
  </div>
</div>


<!--about -->
<div class="container">
  <div class="row">
    <div class="container col-md-6 col-sm-12">
      <h1 class="text-center ffh">О нас</h1>
      <p style="padding: 0px 15px 0px 15px" >Мы <b style="color: dodgerblue">Cloud Nine</b>, компания которая дорожит своей репутацией, производя только качественный продукт с помощью новейших технологий.
        Мы найдем индивидуальный подход к каждому клиенту, и реализуем любые Ваши задумки. </p>
    </div>
    <div class="container col-md-6 col-sm-12" >
      <div class="comment">
        <% @random_comment = Comment.all.shuffle.last %>
        <h1 class="ffh text-center">Отзывы наших клиентов</h1>
        <table>
          <tr>
            <td>
              <a class="link" href="<%= @random_comment.url %>">
                <%= image_tag(@random_comment.logo.url(:medium), width: '75px', height: '75px', class: 'img-circle comment-img ') %>
              </a>
            </td>
            <td style="display: block; padding: 0px 15px 0px 15px">
              <p><%= @random_comment.text %> </p>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="container">
      <div class="col-md-12">
        <br><br><br>
        <h1 class="text-center ffh"  >Хотите заказать у нас проект?</h1>
        <h5 class="text-center">Просто заполните форму и мы с Вами свяжемся</h5>
        <% @work = Work.new %>
        <%= simple_form_for(@work) do |f| %>
            <%= f.error_notification %>
            <div class = 'col-md-6 col-sm-12' style="margin-bottom: 10px">
              <%= f.label 'Ваше имя:' %><br>
              <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class = 'col-md-6 col-sm-12' style="margin-bottom: 10px">
              <%= f.label 'email:' %><br>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class = 'col-md-12 col-sm-12' style="margin-bottom: 10px">
              <%= f.label 'Сообщение:' %><br>
              <%= f.text_area :description, class: 'form-control' %>
            </div>

            <div class="col-md-12 col-sm-12">
              <%= f.button :submit, value: 'Создать', class: 'btn btn-main btn-mr'  %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<footer class="panel-footer">
  <p>©CloudNine 2016<% if Date.today.year != 2016 %> -<%= Date.today.year %> <% end %></p>
</footer>

app/views/projects/new.html.erb
<h1 class="text-center ffh">Новый Проект</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @project.picture.url(:medium) %>
</p>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/about.html.erb
<h1 class="text-center ffh">О нас</h1>
<div class="col-md-12">
  <div class="col-md-7" style=" padding: 0px 15px 0px 15px">
    <h2 class="ffh text-center">Кто мы?</h2>
    <hr />
    <p style="padding: 0px 15px 0px 15px" >Мы <b style="color: dodgerblue">Cloud Nine</b>, компания которая дорожит своей репутацией, производя только качественный продукт с помощью новейших технологий.
      Мы найдем индивидуальный подход к каждому клиенту, и реализуем любые Ваши задумки. </p>
  </div>
  <div class="col-md-4" style="float: right">
    <div class="comment">
      <% @random_comment = Comment.all.shuffle.last %>
      <h2 class="ffh text-center">Отзывы наших клиентов</h2>
      <hr/>
      <table>
        <tr>
          <td>
            <a class="link" href="<%= @random_comment.url %>">
              <%= image_tag(@random_comment.logo.url(:medium), width: '75px', height: '75px', class: 'img-circle comment-img ') %>
            </a>
          </td>
          <td style="display: block; padding: 0px 15px 0px 15px">
            <p><%= @random_comment.text %> </p>
          </td>
        </tr>
      </table>
    </div>

  </div>
</div>

app/views/static_pages/contact.html.erb
<h1 class="text-center ffh">Контакты</h1>
<div class="col-md-6 col-sm-12">
<h2 class="text-center ffh"  >Хотите заказать у нас проект?</h2>
<h5 class="text-center">Просто заполните форму и мы с Вами свяжемся</h5>
  <% @work = Work.new %>
  <%= simple_form_for(@work) do |f| %>
      <%= f.error_notification %>
      <div class = 'col-md-6 col-sm-12' style="margin-bottom: 10px">
        <%= f.label 'Ваше имя:' %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class = 'col-md-6 col-sm-12' style="margin-bottom: 10px">
        <%= f.label 'email:' %><br>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class = 'col-md-12 col-sm-12' style="margin-bottom: 10px">
        <%= f.label 'Сообщение:' %><br>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="col-md-12 col-sm-12">
        <%= f.button :submit, value: 'Создать', class: 'btn btn-main btn-mr'  %>
      </div>
  <% end %>
</div>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center ffh">Заказы</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.name %></td>
        <td><%= work.email %></td>
        <td><%= work.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>